GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsIm5iZiI6MTYyNjU5OTUzOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Im1uLWpkYmMtYXV0aCIsImxhbmd1YWdlIjoiZW4iLCJleHAiOjE2MjY2MDMxMzgsImlhdCI6MTYyNjU5OTUzOCwiaGFpcl9jb2xvciI6ImJyb3duIn0.pjJB4ALz0RKsEtkicbVjsGGdxh8a2Y9eA4qbAKw2Bqk
